// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_l8c1Db4SF21QP2B4zEu3UWGuqWF2XE',
    appId: '1:761260667813:web:89006d64c7f0e2fa82ae4c',
    messagingSenderId: '761260667813',
    projectId: 'chat-app-4cc3b',
    authDomain: 'chat-app-4cc3b.firebaseapp.com',
    storageBucket: 'chat-app-4cc3b.appspot.com',
    measurementId: 'G-4H4SGH47BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEQv62VGl-2bAKZKWXJjMycrWdPeR0l8',
    appId: '1:761260667813:android:3b91a507b497cb0682ae4c',
    messagingSenderId: '761260667813',
    projectId: 'chat-app-4cc3b',
    storageBucket: 'chat-app-4cc3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_cFTRr9Vl0Ji0zmbdat_2tvwrBR19Dg',
    appId: '1:761260667813:ios:4d58094f1935b70d82ae4c',
    messagingSenderId: '761260667813',
    projectId: 'chat-app-4cc3b',
    storageBucket: 'chat-app-4cc3b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_cFTRr9Vl0Ji0zmbdat_2tvwrBR19Dg',
    appId: '1:761260667813:ios:4d666a16950d36c982ae4c',
    messagingSenderId: '761260667813',
    projectId: 'chat-app-4cc3b',
    storageBucket: 'chat-app-4cc3b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
